version: 0.2
env:
  variables:
    # Must match the container name in ECS task definition
    CONTAINER_NAME: "ahtr"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR in $AWS_DEFAULT_REGION
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $ECR_REPO_URI | cut -d/ -f1)
      - COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-$CODEBUILD_SOURCE_VERSION} | cut -c 1-7 || true)
      - IMAGE_TAG=${COMMIT_HASH:-$CODEBUILD_BUILD_NUMBER}
  build:
    commands:
      - echo Building image $ECR_REPO_URI:$IMAGE_TAG
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest
  post_build:
    commands:
      - echo Pushing images
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo Writing imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
